research_task:
  description: >
    Conduct a thorough investigation to gather key company details for UK-registered companies, including the official
    registered company name, address, and website.
    Investigate and determine the year a company was founded and the number of employees it currently has.
    Leverage public company records or other reputable sources to gather this historical and operational data.
    Focus on authoritative sources like Companies House, official websites, and social media profiles to provide
    accurate and reliable data.
    Extract the SIC code that best describes the business activities of the company and categorize the primary industry
    sector of the company.
    Provide a brief and accurate description of the business activities of the company.
    Provide a list with the social media profiles of the company.
    Find the key contacts in the company such as the CEO, CFO, and other relevant individuals.
    Identify which accounting software a company uses by searching through available online resources such as the company
    website or trusted business platforms. Focus on identifying widely used accounting software such Xero, QuickBooks,
    Sage. Some of them provide a list of their partners like https://www.xero.com/advisors/find-advisors for Xero and
    https://proadvisor.intuit.com/app/accountant/search for QuickBooks.
  expected_output: A structured text with of the information you were asked for in paragraphs.
  agent: researcher

convert_to_json_task:
  description: >
    Convert the provided report into a JSON file with the following structure:
    Make sure the report is detailed and contains any and all relevant information including links to the social media
    profiles of the key contacts of the company. Add the email, phone, and LinkedIn profile of the contacts of the company.
    If you cannot get any information, leave "null" as value of the field.

    Ensure the JSON is well-formed and all fields are populated based on the report matching the following structure:
    {{
      "company_name": "type: string; example: 'Top Accounting')",
      "registered_company_name": "type: string; example: 'Top Accounting Ltd')",
      "billing_address": {{
        "town": "type: string; example: 'London')",
        "postcode": "type: string; example: 'SW1A 1AA')",
        "state": "type: string; example: 'London')",
        "address_line_1": "type: string; example: '10 Downing Street')",
        "address_line_2": "type: string; example: 'Westminster')"
      }},
      "sic_code": "type: string; example: '12345')",
      "industry": "type: string; example: 'ACCOUNTING')",
      "description": "type: string; example: 'A top accounting firm in UK providing services to small and medium businesses')",
      "founded_year": "type: integer; example: 2010)",
      "number_of_employees": "type: string; example: '1-10, 11-50, 51-200, 201-500, 501-1000, 1001-5000')",
      "website": "type: string; example: 'https://www.topaccounting.co.uk')",
      "social_media": [
        {{
          "platform": "type: string; example: 'LinkedIn')",
          "url": "type: string; example: 'https://www.linkedin.com/company/topaccounting')"
        }}
      ],
      "key_contacts": [
        {{
          "name": "type: string; example: 'John Doe')",
          "position": "type: string; example: 'CEO')",
          "email": "type: string; example: 'john.doe@topaccounting.co.uk')",
          "phone": "type: string; example: '+44 1234 567890')",
          "linkedin": "type: string; example: 'https://www.linkedin.com/in/johndoe')"
        }}
      ],
      "accounting_softwares": ["type: string; example: xero, quickbooks, sage, freeagent)"]
    }}
  expected_output: >
    A valid JSON file matching the specified structure.
    Format the JSON without '```' and '```json' tags.
    Treat missing information as "null" in the JSON file.
  agent: json_converter
  output_file: company_data.json
